### ISSUE TITLE
Items should not disappear when player has a full inventory

### ISSUE THREAD

**Issue by Matteas-Eden** [Matteas-Eden/roll-for-reaction#28]
**User Story**
As a player, I'd like to keep all items I encounter, so that I may have full control over what I do with said items.

**Acceptance Criteria**

- Items are not lost when found in a chest but the player has a full inventory

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
I'm always frustrated when I find an item in a chest but my inventory is full and that item is lost forever.

**Describe the solution you'd like**
I'd like to be able to come collect an item later if I can't fit it in my inventory at the time I find it.

**Comment by Pyxxil** [comment]
Currently the way this is implemented is that the chest is only populated when the player opens it (which makes the most sense). What this means is that the items are not actually stored inside any chest object, and are merely temporary unless put into the players inventory (where they are then stored indefinitely).

So, this probably requires a little larger change than originally thought because it would require making the chests effectively have their own inventory. Though I'm wondering if implementing them similar to how shops are done may work better, so I'll be looking into them next.

**Comment by Pyxxil** [comment]
Closing this, as it should've been closed with #55, but I forgot to put a closing tag...
